version: '3.8'

services:
  backend:
    build: ./Backend
    ports:
      - "3000:3000"
    volumes:
      - ./Backend/data:/app/data 
    environment:
      NODE_ENV: production
    restart: always

  frontend:
    build: ./Frontend
    ports:
      - "8080:80"
    depends_on:
      - backend